---
- name: Configure apache2 using child playbooks
  hosts: all
  tasks:
    - name: Call child playbooks fro apache2
      include_tasks: "{{item}}"
      with_items:
        - install.yml
        - edit_index.yml
        - restart.yml
        - check_url_response.yml
