---
- name: Configuring apache2/httpd
  hosts: all
  tasks:
    - name: Install apache2 on Ubuntu servers
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install httpd on Centos servers
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "CentOS"
    - name: Edit the index.html file
      copy:
        content: "IntelliQIT"
        dest: /var/www/html/index.html
    - name: Restart apache2 on Ubuntu server
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: Restart httpd on Centos servers
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "CentOS"
    - name: Check apache response on all servers
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.29.249
        - http://172.31.22.183
        - http://172.31.26.185
...





