---
- name: Error Handling
  hosts: all
  tasks:
    - block:
       - name: Install git on ubuntu using apt
         apt:
           name: git
           state: present
           update_cache: yes
      rescue:
        - name: Install git on centos/rhel using yum
          yum:
            name: git
            state: present
            update_cache: yes
