---
# vars file for tomcat
pkg1: tomcat9
pkg2: tomcat9-admin
state1: present
cache1: yes
cache2: no
file1: tomcat-users.xml
dest1: /etc/tomcat9
port1: 8080
port2: 9090
path1: /etc/tomcat9/server.xml
state2: restarted
seconds: 30
server1: "http://172.31.26.185:9090"
server2: "http://172.31.22.183:9090"
status1: 200
